### ISSUE TITLE
Can't install phoityne-vscode

### ISSUE THREAD

**Issue by BigTone2009** [phoityne/hdx4vsc#2]
When I issue the command "stack install phoityne-vscode", I get the following response:-

"Populated index cache.
phoityne-vscode-0.0.27.0: configure
phoityne-vscode-0.0.27.0: build"

But the system hangs there, literally for hours, with no indication of completion.
If I go to the ".stack-work/logs" folder under my stack project, and open the file "phoityne-vscode-0.0.27.0.log", it there says that 9 out of 107 tasks have been compiled but no further.
What is going on?

Not surprisingly, I can't get the Haskell Debugger to work under VSCode v 1.30.1.

[phoityne-vscode-0.0.27.0.log](https://github.com/phoityne/hdx4vsc/files/2712680/phoityne-vscode-0.0.27.0.log)

**Comment by phoityne** [comment]
from log file, seems that you are using it on WindowOS.
Are you using LTS-13?

There is an issue on ghc-8.6.3.
with this version, build will hang.
(because of using template haskell)
https://ghc.haskell.org/trac/ghc/ticket/16057

**Comment by BigTone2009** [comment]
Thank you for responding so quickly, and over the Holiday period, to boot!

I've actually solved the problem by using the Git Bash (MINGW64) command window, rather than the Dos/Windows command window. The Stack command worked fine with no undue delay in processing phoityne-vscode  and haskell-dap, as before, and the Debugger now runs perfectly in Visual Code without any errors. Thank you for a great tool!

```
ghc 8.6.3
git 2.20.1.windows.1
stack 1.9.3
cabal 2.4.1.0
curl 7.63.0
bash 4.4.23(1)
Visual Code 1.30.1
```

**Comment by eof273** [comment]
I'm really new in haskell and in using `ghc`, so maybe I used a stupid way:
I installed `phoityne-vscode` using `--resolver lts-12.10` ([ghc-8.4.3](https://www.stackage.org/lts-12.10));
```
stack install --resolver lts-12.10 phoityne-vscode
```
(`haskell-dap` was installed earlier with my default ghc version (8.6.3));

So now it works great;
