### ISSUE TITLE
feature request - sample launch and task files

### ISSUE THREAD

**Issue by theGhostJW** [phoityne/hdx4vsc#4]
Providing sample / default:

.vscode/tasks.json

.vscode/launch.json

in this repo would be helpful to get new users up and running, particularly new users of vs code.

**Comment by phoityne** [comment]
Thanks for you request.
I will put files and write much better readme.

These files are supposed to be created by vscode, phoityne.
as see in the movie.

![07_construct_dev.gif](https://raw.githubusercontent.com/phoityne/hdx4vsc/master/docs/07_construct_dev.gif)

**Comment by phoityne** [comment]
added [sample configs](https://github.com/phoityne/hdx4vsc/tree/master/configs) and updated readme.
