### ISSUE TITLE
How to add "--with-ghc=haskell-dap" to ghciCmd variable.

### ISSUE THREAD

**Issue by razvan-panda** [phoityne/hdx4vsc#5]
Where in VSCode can I find a `launch.json` that contains the `ghciCmd` variable?

If I open from the menu `Debug` -> `Open Configurations` then I get a `launch.json` which seems to be used for NPM debug:

```js
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
        {
            "name": "Extension Tests",
            "type": "extensionHost",
            "request": "launch",
            "runtimeExecutable": "${execPath}",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/test/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```

**Comment by phoityne** [comment]
Hi.

The launch.json will  be created by vscode
 and be saved in the ".vscode" directory in your stack project directory.

Could you try setting up with this video ?
although it's windows version, but almost same on linux. 

![quick setup](https://raw.githubusercontent.com/phoityne/hdx4vsc/master/docs/07_construct_dev.gif)

Regards.

**Comment by razvan-panda** [comment]
@phoityne In the end I figured out what the issue was. I was looking at at non-Haskell project accidentally. Opening the `launch.json` of a Haskell project shows a correct version of it.

I submitted a PR that clarifies installation steps: https://github.com/phoityne/hdx4vsc/pull/6/files
