### ISSUE TITLE
Debugger keeps loading after clicking "Start Haskell Debugging"

### ISSUE THREAD

**Issue by runeksvendsen** [phoityne/hdx4vsc#7]
When I set a breakpoint in a function, and click "Start Haskell Debugging" on it, the VS Code debugger just keeps loading, without ever breaking at the breakpoint.

Here's a screen capture of the process: 
![hs-debug-720p](https://user-images.githubusercontent.com/1069247/72216691-c77a5780-3524-11ea-99f4-b1cad682a00a.gif)

**Versions:**

|Package|Version|
|--------|--------|
phoityne.phoityne-vscode| 0.0.24
GHC| 8.6.5
VS Code| 1.41.1 (commit 26076a4de974ead31f97692a0d32f90d735645c0)
phoityne-vscode| 0.0.28.0
haskell-dap| 0.0.14.0
ghci-dap| 0.0.13.0
haskell-debug-adapter| 0.0.32.0

**Comment by phoityne** [comment]
Hi.

haskell-debug-adapter might be waiting for an initial prompt from ghci.
Could you confirm that the initial prompt string in the lauch.json is match with actual prompt on ghci ?
```
"ghciInitialPrompt": "Prelude> ",
```

Regards.

**Comment by runeksvendsen** [comment]
Thank you! That was indeed the issue. My ghci prompt is "λ>". Changing the `ghciInitialPrompt` setting to this fixed the issue.
